# Generated by Django 6.0.3 on 2026-03-28 18:03

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='abbreviation',
            new_name='abbr',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slug_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='arena',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='conf',
            field=models.CharField(blank=True, choices=[('East', 'east'), ('West', 'west')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.team_logo_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('stat_type', models.CharField(choices=[('reg', 'Regular Season'), ('post', 'Postseason'), ('career', 'Career')], max_length=10)),
                ('gmp', models.IntegerField()),
                ('mins', models.FloatField()),
                ('pts', models.FloatField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('tpm', models.IntegerField()),
                ('tpa', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('oreb', models.FloatField()),
                ('dreb', models.FloatField()),
                ('reb', models.FloatField()),
                ('ast', models.FloatField()),
                ('stl', models.FloatField()),
                ('blk', models.FloatField()),
                ('tov', models.FloatField()),
                ('pf', models.FloatField()),
                ('plus_minus', models.FloatField(blank=True, null=True)),
                ('fantasy_points', models.FloatField(blank=True, null=True)),
                ('double_doubles', models.IntegerField(default=0)),
                ('triple_doubles', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'unique_together': {('player', 'season', 'team', 'stat_type')},
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('stat_type', models.CharField(choices=[('reg', 'Regular Season'), ('post', 'Postseason')], max_length=10)),
                ('coach', models.CharField(max_length=120)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('gmp', models.IntegerField()),
                ('mins', models.FloatField()),
                ('pts', models.FloatField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('tpm', models.IntegerField()),
                ('tpa', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('oreb', models.FloatField()),
                ('dreb', models.FloatField()),
                ('reb', models.FloatField()),
                ('ast', models.FloatField()),
                ('stl', models.FloatField()),
                ('blk', models.FloatField()),
                ('tov', models.FloatField()),
                ('pf', models.FloatField()),
                ('plus_minus', models.FloatField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'unique_together': {('season', 'team', 'stat_type')},
            },
        ),
    ]
