# Generated by Django 6.0.3 on 2026-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_abbreviation_team_abbr_remove_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, null=True),
        ),
    ]
