# Generated by Django 6.0.3 on 2026-03-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_player_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='double_doubles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='triple_doubles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
