# Generated by Django 6.0.3 on 2026-03-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_playerstats_double_doubles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerStats',
            new_name='PlayerStat',
        ),
        migrations.RenameModel(
            old_name='TeamStats',
            new_name='TeamStat',
        ),
    ]
