# Generated by Django 6.0.3 on 2026-04-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_playerstats_playerstat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='id',
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='ast',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='blk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='dreb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='mins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='oreb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.player'),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='reb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='stl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='tov',
            field=models.IntegerField(),
        ),
    ]
