# Generated by Django 6.0.3 on 2026-04-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_playerstat_id_alter_playerstat_ast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
