# Generated by Django 6.0.3 on 2026-04-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_playerstat_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstat',
            name='fgm',
        ),
    ]
