# Generated by Django 6.0.3 on 2026-04-23 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_playerstat_id_alter_playerstat_ast_and_more'),
        ('games', '0003_alter_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('home_wins', models.IntegerField(default=0)),
                ('road_wins', models.IntegerField(default=0)),
                ('home_losses', models.IntegerField(default=0)),
                ('road_losses', models.IntegerField(default=0)),
                ('conf_rank', models.IntegerField(blank=True, null=True)),
                ('div_rank', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
