# Generated by Django 6.0.3 on 2026-05-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_teamstat_fgm'),
        ('games', '0004_record'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['home_team'], name='games_game_home_te_1a0dde_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['away_team'], name='games_game_away_te_0d68da_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date'], name='games_game_date_b7173e_idx'),
        ),
    ]
